modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "PolyForm Shield License 1.0.0"

[[mods]]
modId = "resourcehack"
version = "${version}"
displayName = "ResourceHack"
authors = "ArcNode"
description = '''

'''
#logoFile = ""

[[dependencies.resourcehack]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcehack]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "resourcehack.mixins.json"
